# Generated by Django 4.2.5 on 2023-10-15 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0012_remove_project_portfolio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectsInPortfolio',
        ),
    ]
